### ISSUE TITLE
"Error accessing service" which is viewable in "Bluetooth LE Explorer"

### ISSUE THREAD

**Issue by ethaniel** [sensboston/BLEConsole#1]
Thank you for an amazing application!

I am interacting with a GoPro. I encountered 2 problems:

**First problem**

In "Bluetooth LE Explorer" I can see the service 61590 and it's characteristics:
![image](https://user-images.githubusercontent.com/941973/57436135-4bc75d00-7269-11e9-880a-851e4cff0595.png)

When I try to access the same service (65190) through BLEConsole, it returns "Error accessing service."
![image](https://user-images.githubusercontent.com/941973/57436227-7ca79200-7269-11e9-9acc-27b0cfca6cd7.png)

**Second problem**

I would like to write directly to characteristic b5f90072-aa8d-11e3-9046-0002a5d5c51b (which is inside the service 6190). I tried following your naming rules, but it didn't work:

![image](https://user-images.githubusercontent.com/941973/57436517-08b9b980-726a-11e9-9ae3-9633f08f5400.png)

It would be easier if I could write to b5f90072-aa8d-11e3-9046-0002a5d5c51b directly (without the "Custom characteristic" or service part).

**Comment by kinetixx** [comment]
You need to remember what type of data you are writing - normally you put hex data.
For that you need to change format to hex like that:
`format hex` - by default in BleConsole format is utf

Writing looks like that:
format hex
write #06/#00 03 17 01 01 - beeping
write #06/#00 03 17 01 00 - no beeping
write #06/#00 01 05 - power off

**Comment by megholm** [comment]
> **First problem**
> 
> In "Bluetooth LE Explorer" I can see the service 61590 and it's characteristics: ![image](https://user-images.githubusercontent.com/941973/57436135-4bc75d00-7269-11e9-880a-851e4cff0595.png)
> 
> When I try to access the same service (65190) through BLEConsole, it returns "Error accessing service." ![image](https://user-images.githubusercontent.com/941973/57436227-7ca79200-7269-11e9-9acc-27b0cfca6cd7.png)

Did you ever find a solution for this? I get the same problem here - I can access the service from the UI explorer (but I'd rather use this CLI)...

BR,
Martin
