### ISSUE TITLE
Send value to go Pro Hero8

### ISSUE THREAD

**Issue by ledaryceti** [sensboston/BLEConsole#10]
Hi,

I wanted to use BLEConsole in order to activate the wifi on a GoPro Hero 8.
In order to do this I need to send a value to a characteristic. The value is 03170101. This value should be converted in byte array and send to the device.
When I do it i do not get any error message but nothing happens on the camera.
For confirmation I tried another similar solution on Debian and it works...
I just wanted to be sure of how the write command should be written. As of know I use : `Write #06/#00 03170101`
Thnaks,

**Comment by kinetixx** [comment]
You need to remember that you put hex data for that, you need to change the format by typing:
`format hex` - default is utf

Than you put the data like that (with space)
`03 17 01 01`

Whole code looks like that

format hex
write #06/#00 03 17 01 01 - beep
write #06/#00 03 17 01 00 - no beep
