### ISSUE TITLE
BLE Console crashes while performing the subs command

### ISSUE THREAD

**Issue by abeldsouza** [sensboston/BLEConsole#13]
Dear Community,

I came across this application and found it quite good. So i started testing this to see if it would be suitable for me to use in my project. I found one issue that i am not sure of and need some help. 

After disconnecting from a device, reconnecting to the device again will invariable report a device unreachable error or a crash just after subscribing to the notify service. Log file attached. 

Any help or pointers would be greatly appreciated. Since i can just reopen the app and connect i dont believe its an issue on the peripheral side. Also i have used outer android based ble apps to connect and disconnect multiple time siwthout any issues.

Thanks.
[BLEConsoleLog.txt](https://github.com/sensboston/BLEConsole/files/7275153/BLEConsoleLog.txt)
Abel.

**Comment by sensboston** [comment]
Sorry, Abel, I can't help you: literally, I don't have any BLE device with notifications now. When I tested that feature, everything worked as expected; according to the log you provided, target BLE device object was closed ('cause of some unknown reasons) during processing notification event.
Try to install Visual Studio (community edition, it's free) and debug app by yourself.

**Comment by abeldsouza** [comment]
@sensboston Thanks for your reply. yeah I have compiled the source and doing some enhancements. Will try and debug this. Was just hoping to get some inputs in case you have seen this earlier.

![image](https://user-images.githubusercontent.com/90755888/135989182-ac2ccc0e-9e63-41ac-b2cc-5147a5fe7720.png)
Have added a byte counter and run time tracking.

Thanks,
Abel.

**Comment by sensboston** [comment]
Hey, Abel, what are these weird device names from 05 to 09? It looks like a bug in the app, or just incorrect configured BLE devices.

**Comment by abeldsouza** [comment]
Hey, I am not sure. These are just random devices that the ble scan picked up. 

![image](https://user-images.githubusercontent.com/90755888/136126288-8f71dfdb-b58b-479a-969d-73a8f595adc4.png)
