### ISSUE TITLE
Sending Char(acters)

### ISSUE THREAD

**Issue by sponi78** [sensboston/BLEConsole#14]
I connected to a ble device(#03), it has a service (#02) i want to use a characteristic (#00 or #01) to send a char ("?"), if i send this char the  bluetooth device will send me a string. 
BLE: stat
Device Control_Unit is connected.
Available services:
#00: GenericAccess
#01: GenericAttribute
#02: Custom Service: 39df7777-b1b4-b90b-57f1-7144ae4e4a6a
Selected service: Custom Service: 39df7777-b1b4-b90b-57f1-7144ae4e4a6a
Available characteristics:
#00: Custom Characteristic: 39df9999-b1b4-b90b-57f1-7144ae4e4a6a          N
#01: Custom Characteristic: 39df8888-b1b4-b90b-57f1-7144ae4e4a6a         W
BLE:
i have already set format to ASCII
how can i get this work? Here is what i send:
Current display format: ASCII
BLE: read #02/#01 ?
Invalid device number 01 ?
Invalid characteristic #01 ?
BLE:

**Comment by sensboston** [comment]
If you wanna read something, use function **Read** (for already opened device) with params:  service_name char_name
If you wanna to write, use **Write**, with similar parameters but don't forget to add value to write
