### ISSUE TITLE
little bug in prompt?

### ISSUE THREAD

**Issue by eried** [sensboston/BLEConsole#18]
I have not been able to understand why there is this little error in the prompt printing (1 "BLE:" moves to the next line):
![image](https://user-images.githubusercontent.com/1091420/170266654-1701ccd7-977c-443d-bab2-b12110ea7b96.png)

I think is when data is received too fast

**Comment by sensboston** [comment]
This simple app isn't designated for fast BLE events processing - 'cause it should output data to console but this is slow.
