### ISSUE TITLE
I want to get the battery information

### ISSUE THREAD

**Issue by jzeb** [sensboston/BLEConsole#19]
As shown in the figure, how can I get the information of battery quantity and how to send instructions
![image](https://user-images.githubusercontent.com/4947249/170910898-162112c0-38dd-4c7d-9ab8-30a019ca2a58.png)

![image](https://user-images.githubusercontent.com/4947249/170911769-8a93d528-f382-4e52-831d-db4cede231d9.png)

Why isn't it the power information? It's just a "P"?

**Comment by jzeb** [comment]
Thank you

**Comment by sensboston** [comment]
Closed
