### ISSUE TITLE
 direct use BLEConsole in cmd

### ISSUE THREAD

**Issue by yangmeishu** [sensboston/BLEConsole#20]
how to direct use BLEConsole.exe in cmd,do not in BLEConsole.exe . like  C:\BLEConsole.exe list,then output ble device list

**Comment by sensboston** [comment]
**BLEConsole.exe** accept standard input for a command script file (I already provided a very good sample in documentation). Before asking so trivial stuff, you should learn first how to use and work with cmd.exe or PowerShell, i.e. with any command shell in Windows. BLEConsole.exe is a standard console app (but advanced one), nothing more.
