### ISSUE TITLE
Support Request: Is there any way to detect errors or retry?

### ISSUE THREAD

**Issue by gritstub** [sensboston/BLEConsole#24]
Thanks for this tool! It's very helpful for automating control of my RGB strips.

Sometimes my devices respond with:
`Device <Device> is unreachable.`

Is there a good way to detect that this happened, and retry?  Maybe with exit codes or just using if/else and repeating the code a few times?

Perhaps increasing the timeout that might help?

**Comment by jpstotz** [comment]
If you want to script BLE communication I would recommend to try the Python library [Bleak](https://bleak.readthedocs.io/en/latest/). It is IMHO better for scripting and you have full control on what to do in case of errors. 
The Bleak project contains some ready-to-use sample scripts https://github.com/hbldh/bleak/tree/develop/examples

BLEConsole is better for interactive exploring BLE devices.

**Comment by gritstub** [comment]
I will give that a try! Otherwise, BLEConsole has been working great with the < command input. Thanks for the advice and software!
