### ISSUE TITLE
Unsubscribe of notifications does not work

### ISSUE THREAD

**Issue by jpstotz** [sensboston/BLEConsole#26]
In my tests on Windows 10 the command to unsubscribe from e.g. a notification does not work (also affects indications):

`await sub.WriteClientCharacteristicConfigurationDescriptorAsync(GattClientCharacteristicConfigurationDescriptorValue.None);`
https://github.com/sensboston/BLEConsole/blob/master/BLEConsole/Program.cs#L1200

Once you execute the command above the control flow stops and exit `Unsubscribe`, so it seems to trigger some internal Exception but I wasn't able to catch an Exception.

The command itself seems to be correct just Windows acts totally unexpected. For this reason the `unsubs all` command does not work at least on the computers I had tested it on. 

My guess is that this is some sort of Windows/.net bug.

**Comment by sensboston** [comment]
I need to find/purchase BLE device to test this behavior; will fix as I get one.

**Comment by jpstotz** [comment]
A lot of smartphones are capable to provide an GATT server, so apps can implement the gatt services.

Apps like [nRF Connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp) or [BLE Peripheral Simulator](https://play.google.com/store/apps/details?id=io.github.webbluetoothcg.bletestperipheral) can simulate GATT servers and services including notifications. 

Both apps are also on GitHub so it is easy to change a notification to an indication. That is how I did my tests, having a button that triggers a notification/indication makes it easier to test instead of having to wait for an notification/indication.

**Comment by sensboston** [comment]
OK, I'll try when I have time and mood to do.
