### ISSUE TITLE
Feature Request: Connect to device via bluetooth address

### ISSUE THREAD

**Issue by UCSIG** [sensboston/BLEConsole#27]
Hi,

I have a lot of ble devices with the same advertising name.
It would be cool if there was a way of connecting to them using the 6-byte bluetooth address. At the moment I don't really have a way of differentiating between the devices using just the name.

Other than that its a really helpful application for testing various communication protocls during development.
Thanks for your effort!

**Comment by sensboston** [comment]
@UCSIG, I'm very busy these times with daily job and new, exciting homebrew project. So, be my guest, add changes and issue a PR - I'll be glad to merge (technically it's really simple).

**Comment by UCSIG** [comment]
Okay, I'll give it a try in the coming days!

What do you think could be the best way to distinguish a ble device name from a ble address using the `open` command?

To distinguish between a ble device name and the position in the discovered devices list a '#' character is used.  
One way could be to just check whether the ':' is found at the right indices in the string, it should be at index [2, 5, 8, 11, 14], using the format `xx:xx:xx:xx:xx:xx`.
What do you think?
