### ISSUE TITLE
Latest build?

### ISSUE THREAD

**Issue by FaBjE** [sensboston/BLEConsole#29]
I was planning on using the BLE Console for some simple device interaction.
But I'm not sure where I can find the latest build.

The releases page (and click once) all refer to 1.5.6. But according to the releases page, this is from Mar 17, 2018.
The source-code seems to have advanced a lot beyond this point.

Can someone be so kind to create a release/build?

I've tried compiling the sources, but as the compile_hints.txt states I got down the rabbit hole of Windows SDK Kit versions and I'm afraid I'm going to introduce more issues rather than fix them.

**Comment by sensboston** [comment]
I just rebuilt BLEConsole and published a new release 1.6.0, enjoy!
https://github.com/sensboston/BLEConsole/releases/tag/v1.6.0
