### ISSUE TITLE
Why would ls get a device that no longer exists?

### ISSUE THREAD

**Issue by LunaAsuka** [sensboston/BLEConsole#38]
1. I see in the README that there is a possibility that the device that ls fetches may not currently exist, but I don't understand why ls would fetch a device that is not present in the current period, is it because ls isn't really scanning for surrounding devices? If so, is it possible for BLEConsole to actively scan for surrounding devices?

2. Also, I noticed that BLEConsole supports using the arrow keys to fetch the input history, but why is it that a BLEConsole that is closed and then restarted can also fetch the previous input history?

By the way, I've never written C#, so I don't know much about any of this, and would appreciate a explanation, thanks!

**Comment by sensboston** [comment]
Hi, @LunaAsuka

as for #1: an answer is **Windows cashing**. Don't ask me, ask M$ 😉 

as for #2: **BLEConsole** is a standard Windows console app (can be used for automation etc.) so it "supports" (thanks Mr. B.Gates 😜) all the features what the regular console app supposed to support (there is no additional features added).
