### ISSUE TITLE
How to send a file to BLE device?

### ISSUE THREAD

**Issue by nikhilabhi** [sensboston/BLEConsole#6]
Hello everyone,
I could able to send some string data to BLE device, which is already paired. 
Now I want to send a text file which is already saved in my local drive. But i could not load file from my Local drive. Can anyone suggest me how to send local file data to ble device?

**Comment by ejhpas** [comment]
> Hello everyone,
> I could able to send some string data to BLE device, which is already paired.
> Now I want to send a text file which is already saved in my local drive. But i could not load file from my Local drive. Can anyone suggest me how to send local file data to ble device?

Salutations, nikhilabhi. You can send strings using a text file by pointing it to BLEConsole.exe in a command prompt. It has to be the executable and not the application manifest, that means you need to build BLEConsole yourself. Once you've done that, open a command prompt and run:

`BLEConsole.exe < cmd.txt > data.txt`

where cmd.txt is a text file with your commands to be sent to BLEConsole.exe, i.e. 
```
foreach 
        open "bledevicename" 
        set "servicename"
        read #00
```

and data.txt is your data coming from the ble device.
