### ISSUE TITLE
Not able to reach out installation download webpage.

### ISSUE THREAD

**Issue by pranjalchanda** [sensboston/BLEConsole#7]
When trying to access [Install via ClickOnce](http://senssoft.com/BLEConsole/BLEConsole.application)  The webpage blocks access. 
![image](https://user-images.githubusercontent.com/55234984/83373536-4bef4900-a3e6-11ea-8db9-65576b70d409.png)

Please help me with the installation.

**Comment by sensboston** [comment]
Check your internet connection or antivirus/proxy behaviour; download link still works for me.
