### ISSUE TITLE
How to send bluetooth basic instruction to device

### ISSUE THREAD

**Issue by zadss760** [sensboston/BLEConsole#8]
Hello everyone,

I want to send a basic ASCII instruction to a bluetooth device and I can't find how to do that with BLEConsole...

Could you help me please ?

Thank you for your help ! 👍

**Comment by sensboston** [comment]
Sorry, but there is no "basic ASCII instruction" therm in bluetooth. If your bluetooth device supports BLE, you can use this app (and writing is pretty simple: open device, set BLE service (property), set data format (ASCII or UTF8) and use command **write**). If your device is RFComm (bluetooth serial or any other kind of BT), this app will not work with.
