### ISSUE TITLE
Can't receive new characteristic value when set to indication

### ISSUE THREAD

**Issue by vucaly** [sensboston/BLEConsole#9]
After subscribing to characterisitc which is set to the indication property the application does not seem to receive the event on value change.
The application works very well when the characteristic is set to the notification propery.

**Comment by sensboston** [comment]
Notification are worked fine, it's 100% tested: I've created and used BLEConsole a few years ago especially for handling notifications from BLE devices I worked with. I can suggest you to change data format (by default, it's UTF8) to hex or binary: might be, you're receiving notifications but data is "invisible" for console (non-printed characters received).
